config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    get 'gists/index'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :authenticate_user!
  before_action :set_test, only: %i[new create]
  before_action :set_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question), notice: 'Add new question!'
    else
      render :new
    end
  end

  def show
    # @answers = @question.answers
  end

  def edit
    # empty
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question), notice: 'Update question!'
    else
      render :edit
    end

  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test), notice: 'Delete question!'
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found', status: 404
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.test.title

    header = if question.new_record?
             "Create New #{title} Question"
           else
             "Edit #{title} Question"
           end

    content_tag('h1', header)
  end
end

app/views/questions/_form.html.erb
<%= form_with model: [@test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :question_body %>
  </p>

  <p>
    <%= form.collection_select :test_id, Test.all, :id, :title, prompt: true %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/questions/_question.html.erb
<tr>

  <td><%= question.body %></td>
  <td><%= question.test.title %></td>
  <td><%= link_to 'Show', question_path(question) %> |</td>
  <td><%= link_to 'Edit', edit_question_path(question) %> |</td>
  <td><%= link_to 'Delete',
                  question_path(question),
                  method: :delete,
                  data: {confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/questions/show.html.erb
<h1>
  Question:
  <%= @question.body %>
</h1>

<h3>
  Test:
  <%= @question.test.title %>
</h3>

<h3>Answers</h3>
<%= link_to 'New answer', new_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>
<%= 'NO ANSWERS' if @question.answers.blank? %><br>
<%= link_to 'Back', admin_test_path(@question.test) %>