config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    get 'gists/index'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update
  before_validation :before_validation_set_timer, on: :create

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def success?
    percentage >= SUCCESS
  end

  def time_is_out?
    (Time.now - self.created_at) > test.time_limit if test.time_limit
  end

  def percentage
    self.correct_questions * 100 / test_questions_count
  end

  def test_questions_count
    test.questions.count
  end

  def test_question_index
    test.questions.index(current_question) + 1
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def before_validation_set_timer
    self.timer = test.time_limit
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show result update gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids]) # можно опустить после time_is_out? чтобы не засчитывать

    if @test_passage.time_is_out?
      flash[:alert] = 'Time is out!'
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
      return # чтобы выйти и не проверять completed?
    end

    if @test_passage.completed?
      BadgeAwardService.new(@test_passage).call

      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    question = @test_passage.current_question
    service = GistQuestionService.new(question)
    response = service.call
    url = response.html_url

    flash = if service.success?
              current_user.gists.create(question: question, url: url)
              { notice: t('.success', url: url) }
            else
              { alert: t('.failure') }
            end

    redirect_to @test_passage, flash
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<% if @test_passage.success? %>
  <h2 style="color: green"><%= t('.success') %></h2>
<% else %>
  <h2 style="color: red"><%= t('.failure') %></h2>
<% end %>

<h3><%= t('.result', result: @test_passage.percentage) %></h3>

<%= link_to t('actions.back'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<%= render 'shared/timer' %><br>
<%= render 'shared/progress_bar', test: @test, current_question: @test_passage.current_question %>
<hr>
<p>
  <h3><%= @test_passage.current_question.body %></h3>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p><%= link_to t('.savegist'), gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('actions.next') %></p>
<% end %>