config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    get 'gists/index'
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord

  MAX_ANSWERS = 4

  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_to_question, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_answers_to_question
    errors.add(:question, 'can not have more than 4 answers') if question.answers.count >= MAX_ANSWERS
  end

  # def question_answers
  #   question.answers
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULES = %w[category_complete level_complete first_attempt_complete].freeze

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges, dependent: :destroy

  validates :title, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  #validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy
  belongs_to :author, class_name: 'User', optional: true

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level }
  validates :level, numericality: { greater_than_or_equal_to: 0,
                                    only_integer: true }

  scope :tests_by_category, -> (category) { joins(:category).where(categories: { title: category }) }
  scope :easy, -> { where(level: 0..1) }
  scope :middle, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY)}

  def self.titles_by_category(category)
    tests_by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update
  before_validation :before_validation_set_timer, on: :create

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def success?
    percentage >= SUCCESS
  end

  def time_is_out?
    (Time.now - self.created_at) > test.time_limit if test.time_limit
  end

  def percentage
    self.correct_questions * 100 / test_questions_count
  end

  def test_questions_count
    test.questions.count
  end

  def test_question_index
    test.questions.index(current_question) + 1
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def before_validation_set_timer
    self.timer = test.time_limit
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges, dependent: :destroy

  # validates :login, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
                    uniqueness: true

  scope :tests_by_level, -> (level) { tests.where(level: level) }

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test, only: :start

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Test was not found', status: 404
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
   FLASH_KEYS = {  'alert' => :danger, 'notice' => :primary }.freeze

  def flash_class(key)
    FLASH_KEYS[key] || :secondary
  end

  def current_year
    Date.today.year
  end

  def github_url(author, repo)
    name = repo.blank? ? author : repo

    link_to name,
            "https://github.com/#{author}/#{repo}",
            target: '_blank'
  end
  
  def flash_message(name)
    if flash[name]
      content_tag :p, flash[name], class: "flash #{name}"
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gist_helper.rb
module GistHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.test.title

    header = if question.new_record?
             "Create New #{title} Question"
           else
             "Edit #{title} Question"
           end

    content_tag('h1', header)
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :medium, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %><br>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %><br>
    </div>
    <div class="container">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %><br>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %><br>
    </div>
    <div class="container">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'alert alert-danger', role: 'alert', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.present? %>
  <%flash.each do |key, message| %>
    <div class="alert alert-<%= flash_class(key) %>" role="alert">
      <%= content_tag :p, message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div>
  <hr>
  <p class="card-text"><small class="text-muted">
    Copyright <%= current_year %><br>
    Project: <%= github_url('iL53n', 'test-guru') %>
    by: <%= github_url('iL53n', '') %><br>
    Application for creating tests.<br>
    Educational project in an online school
    <%= link_to  'Thinknetica',
                 'https://thinknetica.com/', target: '_blank'%>
    </small>
  </p>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand" href="#">
    <%= image_tag 'ruby_logo.png', size: "33x35", alt: "RubyLogo" %>
    <%= link_to  'TestGuru', root_path, class: 'navbar-brand' %>
  </span>

  <% if user_signed_in?%>
    <% if current_user.admin? %>
      <li class="navbar-nav nav-item">
        <a><%= link_to t('.admin'), admin_tests_path, class: 'nav-link' %></a>
      </li>
      <li class="navbar-nav nav-item">
        <a><%= link_to t('.gists'), admin_gists_index_path, class: 'nav-link' %></a>
      </li>
      <li class="navbar-nav nav-item">
        <a><%= link_to t('.badges'), admin_badges_path, class: 'nav-link' %></a>
      </li>
    <% else %>
      <li class="navbar-nav nav-item">
        <a><%= link_to t('.badges'), badges_path, class: 'nav-link' %></a>
      </li>
      <li class="navbar-nav nav-item">
        <a><%= link_to t('.feedback'), new_feedback_path, class: 'nav-link' %></a>
      </li>
    <% end %>
  <% end %>

  <span class="navbar-text" >
    <% if user_signed_in? %>
      <small class="text-muted">
        Welcome, <b><%= current_user.first_name %></b> Guru!<br>
      </small>
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.login'), new_user_session_path %> |
      <%= link_to t('.registration'), new_user_registration_path %><br>
    <% end %>
  </span>
</nav>

app/views/shared/_progress_bar.erb
<div class="progress-bar">
  <%= content_tag :div, " - #{@test_passage.test_question_index}/#{@test_passage.test_questions_count} - ",
                  id: 'progress',
                  data: { questions_count: @test_passage.test_questions_count,
                          question_number: @test_passage.test_question_index - 1} %>
</div>

app/views/shared/_progress_bar.html.erb
<div class="progress-bar">
  <%= content_tag :div, " - #{@test_passage.test_question_index}/#{@test_passage.test_questions_count} - ",
                  id: 'progress',
                  data: { questions_count: @test_passage.test_questions_count,
                          question_number: @test_passage.test_question_index - 1} %>
</div>

app/views/shared/_timer.html.erb
<%= content_tag :div, '',
                id: 'timer',
                data: { end_time: @test_passage.created_at.to_i + @test_passage.timer.to_i } %>