config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    get 'gists/index'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord

  MAX_ANSWERS = 4

  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_to_question, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_answers_to_question
    errors.add(:question, 'can not have more than 4 answers') if question.answers.count >= MAX_ANSWERS
  end

  # def question_answers
  #   question.answers
  # end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :authenticate_user!
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :set_question, only: %i[new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_answer_not_found

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), notice: 'Add new answer!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer), notice: 'Update answer!'
    else
      render :edit
    end
  end


  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question), notice: 'Delete answer!'
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def rescue_with_answer_not_found
    render plain: 'Answer was not found', status: 404
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li>
  <%= answer.body %>
  <%= '- correct'  if answer.correct? %><br>
  <%= link_to 'Show', answer_path(answer) %> |
  <%= link_to 'Edit', edit_answer_path(answer) %> |
  <%= link_to 'Delete',
                  answer_path(answer),
                  method: :delete,
                  data: {confirm: 'Are you sure?'} %>
</li>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', question_path(@answer.question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', question_path(@answer.question) %>

app/views/answers/show.html.erb
<h1>
  Question:
  <%= @answer.question.body %>
</h1>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', question_path(@answer.question) %>